version: "3.8"

services:
  app:
    image: trinhviethoang16/turn-base:latest
    container_name: turn-base
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: turn-base-mongo
    volumes:
      - ./data/database:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=turn-base
